language: node_js
node_js:
  - 12.18.4
script:
  - node index.js
deploy:
 provider: releases
 api_key: "28d61230cd742276a9160777675f83a35217d315"
 file: index.js
 skip_cleanup: true
 on:
  tags: false
  branch: main
